--IF NO UNIQUE ID IN TABLE:
ALTER TABLE TABLENAME ADD ID INT IDENTITY(1,1)  

--SPECIFY UNIQUE COLUMNS (AS MANY AS NECESSARY) AND DELETE DUPLICATE RECORDS
DELETE FROM TABLENAME WHERE ID NOT IN (SELECT MIN(ID) FROM TABLENAME GROUP BY column1, column2, column3, column4, column5, column6)
